name: Release TEDI React library

on:
  push:
    branches:
      - rc
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Disable ESLint problem matcher
        run: echo "::remove-matcher owner=eslint::"

      - name: Lint
        run: |
          npm ci --cache .npm --prefer-offline
          npm run lint:ci

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Test
        run: |
          npm ci --cache .npm --prefer-offline
          npm run test

  chromatic:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/rc' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          npm ci --cache .npm --prefer-offline
      - name: Build Storybook
        run: |
          npm run build:sb
      - name: Publish to Chromatic
        run: |
          CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_TOKEN }} npm run chromatic

  build-and-deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Build and publish npm package
        run: |
          HUSKY=0
          npm ci
          npm run build
          ls -la dist
          git pull
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-to-rc:
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Merge main into rc
        run: |
          git fetch origin rc
          git checkout rc
          git merge origin/main --no-edit || true
          git push origin rc
